"""合规审查引擎：内置硬校验 + 知识库动态规则 + LLM 软审查。

审查口径对齐 2026-03-15 新规：三重一致性、AI 声明与原创性、鉴别材料格式硬要求。
输出 blocker（必须修复）/ warning（强烈建议修复）两级。
"""
import re
from datetime import date
from typing import Any, Dict, List

from .. import database as db
from .. import llm
from . import code_engine, kb_service, prompts

FORBIDDEN_NAME_WORDS = re.compile(r"(中国|国家|中央|最高|第一品牌|国家级|百强|驰名)")

AI_TRACE_RE = re.compile(
    r"(?i)(auto[\s-]?generated|generated by|created by AI|作为AI|AI助手|语言模型|ChatGPT|Copilot)")
TODO_RE = re.compile(r"(?i)(TODO\s*[:：]|FIXME|待实现|待补全|此处省略)")

NAME_SUFFIX_RE = re.compile(r"(系统|软件|平台|App|APP|应用程序|管理软件|工具|引擎)$")
VERSION_RE = re.compile(r"^V\d+(\.\d+){0,2}$")


def _issue(level: str, category: str, code: str, message: str, suggestion: str,
           source: str = "builtin") -> Dict[str, Any]:
    return {"level": level, "category": category, "code": code, "message": message,
            "suggestion": suggestion, "source": source}


async def run_review(project_id: int, include_llm: bool = True) -> Dict[str, Any]:
    project = db.get_project(project_id)
    if not project:
        raise ValueError("项目不存在")
    issues: List[Dict[str, Any]] = []
    full_name = (project.get("full_name") or "").strip()
    version = (project.get("version") or "").strip()

    # ---------- 1. 项目信息 ----------
    if not full_name:
        issues.append(_issue("blocker", "材料一致性", "P-NAME",
                             "软件全称为空", "在项目信息中填写软件全称"))
    elif not NAME_SUFFIX_RE.search(full_name):
        issues.append(_issue("warning", "材料一致性", "P-SUFFIX",
                             f"软件名称“{full_name}”不是以 系统/软件/平台/App/工具 等结尾",
                             "改为规范命名，例如“XX数据同步系统”"))
    if full_name and FORBIDDEN_NAME_WORDS.search(full_name):
        issues.append(_issue("blocker", "材料一致性", "P-FORBID",
                             "软件名称含禁用词（中国/国家/中央/最高级等）",
                             "去除禁用词后重新生成全部材料"))
    if not VERSION_RE.match(version or ""):
        issues.append(_issue("blocker", "格式规范", "P-VER",
                             f"版本号“{version}”不符合 V1.0 格式",
                             "版本号改为 V主版本.次版本（如 V1.0），三处材料自动同步"))
    if not (project.get("completion_date") or "").strip():
        issues.append(_issue("blocker", "材料一致性", "P-DATE",
                             "开发完成日期未填写", "填写真实开发完成日期"))
    else:
        try:
            d = date.fromisoformat(project["completion_date"])
            if d > date.today():
                issues.append(_issue("blocker", "材料一致性", "P-DATE-F",
                                     "开发完成日期晚于今天", "改为不晚于今天的真实日期"))
            pub = (project.get("publish_date") or "").strip()
            if pub and pub != "未发表":
                try:
                    if date.fromisoformat(pub) < d:
                        issues.append(_issue("blocker", "材料一致性", "P-DATE-O",
                                             "首次发表日期早于开发完成日期",
                                             "核对日期：完成日期 ≤ 发表日期"))
                except ValueError:
                    pass
        except ValueError:
            issues.append(_issue("warning", "格式规范", "P-DATE-FMT",
                                 "开发完成日期格式异常", "使用 YYYY-MM-DD 格式"))
    if (project.get("dev_type") or "独立开发") != "独立开发":
        issues.append(_issue("warning", "材料缺失", "P-AGREE",
                             f"开发方式为{project['dev_type']}，需附经签字盖章的开发协议",
                             "准备合作/委托开发协议扫描件随材料提交"))

    # ---------- 2. 源代码 ----------
    files = db.get_source_contents(project_id)
    if not files:
        issues.append(_issue("blocker", "材料缺失", "C-NONE",
                             "尚未导入源代码", "在“源代码”页粘贴或上传代码文件"))
        pages_info = {"pages": [], "total_lines": 0, "pages_submitted": 0, "mode": "all"}
    else:
        pages_info = code_engine.build_pages(files)
        total = pages_info["total_lines"]
        if total < config_min_lines():
            issues.append(_issue("blocker", "格式规范", "C-TOO-FEW",
                                 f"源代码仅 {total} 行，不足一页（50行）",
                                 "导入完整项目源代码，或补充功能模块代码"))
        elif total < 3000:
            issues.append(_issue("warning", "AI声明与原创性", "C-THIN",
                                 f"源代码共 {total} 行（<3000行）",
                                 "2026 审查口径建议自研核心代码不少于3000行；不足时建议补充核心模块实现"))
        ok, last = code_engine.last_page_ends_ok(pages_info["pages"])
        if pages_info["pages"] and not ok:
            issues.append(_issue("warning", "格式规范", "C-END",
                                 f"源代码末页最后一行不是结束符（…{last}）",
                                 "确保代码完整、最后一行为函数/程序结束（如 }}）"))
        code_all = "\n".join(f.get("content", "") for f in files)
        hit = AI_TRACE_RE.search(code_all)
        if hit:
            issues.append(_issue("blocker", "AI声明与原创性", "C-AITRACE",
                                 f"源代码存在明显 AI 生成痕迹词（{hit.group(0)}）",
                                 "删除该类注释/字样；核心注释改写为设计意图说明"))
        hit2 = TODO_RE.search(code_all)
        if hit2:
            issues.append(_issue("warning", "AI声明与原创性", "C-TODO",
                                 f"源代码存在未完成标记（{hit2.group(0)}）",
                                 "全局清理 TODO/待实现占位，确保代码可完整运行"))

    # ---------- 3. 文档鉴别材料 ----------
    manual = db.get_doc(project_id, "manual") or db.get_doc(project_id, "design")
    if not manual:
        issues.append(_issue("blocker", "材料缺失", "M-NONE",
                             "尚未生成操作说明书/设计说明书",
                             "在“材料生成”页生成（有界面→操作说明书，无界面→设计说明书）"))
    else:
        if "【截图占位" in (manual.get("content") or ""):
            issues.append(_issue("warning", "格式规范", "M-SHOT",
                                 "说明书仍存在未替换的截图占位框",
                                 "导出 docx 后把占位框替换为真实界面截图（清晰、无水印）再打印"))
        body_lines = len([ln for ln in (manual.get("content") or "").split("\n") if ln.strip()])
        if body_lines < 300:
            issues.append(_issue("warning", "功能描述不足", "M-THIN",
                                 f"说明书正文仅约 {body_lines} 行，篇幅偏薄",
                                 "补充模块操作步骤与常见问题，目标正文不少于 450 行（约15页）"))

    # ---------- 4. 申请表与 AI 声明 ----------
    form = db.get_doc(project_id, "form")
    if not form:
        issues.append(_issue("blocker", "材料缺失", "F-NONE",
                             "尚未生成申请表预填内容", "在“材料生成”页生成申请表字段"))
    else:
        meta = form.get("meta") or {}
        data = meta.get("data") or {}
        mf = str(data.get("main_functions_desc") or "")
        dp = str(data.get("development_purpose") or "")
        if len(mf.replace(" ", "")) < 500:
            issues.append(_issue("blocker", "功能描述不足", "F-FUNC",
                                 f"主要功能描述仅 {len(mf.replace(' ', ''))} 字（新规要求不少于500字）",
                                 "重新生成申请表，或人工扩写后同步到官网申请表"))
        if len(dp.replace(" ", "")) < 500:
            issues.append(_issue("blocker", "功能描述不足", "F-PURP",
                                 f"开发目的仅 {len(dp.replace(' ', ''))} 字（要求不少于500字）",
                                 "重新生成申请表，按'解决什么场景问题→如何解决'结构扩写"))
    declaration = db.get_doc(project_id, "declaration")
    if not declaration:
        issues.append(_issue("warning", "AI声明与原创性", "D-NONE",
                             "尚未生成 AI 使用情况声明（2026-03-15 新规必备）",
                             "在“材料生成”页生成 AI 声明，并准备 Git 记录等过程证据"))
    if not db.get_doc(project_id, "evidence"):
        issues.append(_issue("warning", "AI声明与原创性", "E-NONE",
                             "尚未生成开发过程记录（证据链材料）",
                             "生成开发过程记录并留存 Git 提交记录备查"))

    # ---------- 5. 知识库动态规则 ----------
    targets = {
        "full_name": full_name, "version": version,
        "main_functions": (project.get("main_functions") or "") + "\n" +
                          (str((form or {}).get("meta", {}).get("data", {}).get("main_functions_desc", ""))),
        "source": "\n".join(f.get("content", "") for f in files),
        "manual": (manual or {}).get("content", "") or "",
        "form": str(((form or {}).get("meta", {}) or {}).get("data", {})),
    }
    rules = kb_service.active_rules(project_id)
    issues += kb_service.run_regex_rules(rules, targets, project_id)

    # ---------- 6. LLM 软审查 ----------
    llm_notes: List[Dict[str, Any]] = []
    if include_llm and llm.configured() and files and form:
        try:
            kb_text = await kb_service.get_kb_context(project_id)
            samples = []
            for f in files[:5]:
                samples.append(f"### {f['filename']}\n" + code_engine.snippet(f["content"], 60))
            analysis_doc = db.get_doc(project_id, "analysis") or {}
            ctx = {
                "project": project,
                "kb_text": kb_text,
                "code_samples": "\n\n".join(samples),
            }
            form_data = ((form.get("meta") or {}).get("data") or {})
            form_summary = "\n".join(f"{k}: {str(v)[:400]}" for k, v in form_data.items())
            manual_excerpt = (manual or {}).get("content", "")[:3000]
            msgs = prompts.review_soft_messages(ctx, manual_excerpt, form_summary)
            out = await llm.chat_json(msgs, max_tokens=2000)
            for it in (out.get("issues") or [])[:10]:
                level = "blocker" if it.get("level") == "blocker" else "warning"
                llm_notes.append(_issue(level, str(it.get("category", "其他")), "LLM",
                                        str(it.get("message", ""))[:300],
                                        str(it.get("suggestion", ""))[:300], source="llm"))
        except Exception as e:  # LLM 失败不阻断硬审查结果
            llm_notes.append(_issue("warning", "其他", "LLM-ERR",
                                    f"LLM 软审查未完成：{str(e)[:200]}",
                                    "可配置 LLM 后重试，硬校验结果不受影响", source="llm"))
    issues += llm_notes

    blockers = [i for i in issues if i["level"] == "blocker"]
    warnings = [i for i in issues if i["level"] == "warning"]
    passed = len(blockers) == 0 and bool(files) and bool(form)
    report_id = db.create_report(project_id, passed, len(blockers), len(warnings), issues)
    return {"report_id": report_id, "passed": passed,
            "blockers": len(blockers), "warnings": len(warnings),
            "issues": issues,
            "source_doc": {"pages_submitted": pages_info.get("pages_submitted", 0),
                           "total_lines": pages_info.get("total_lines", 0),
                           "mode": pages_info.get("mode", "all")}}


def config_min_lines() -> int:
    from .. import config
    return config.CODE_LINES_PER_PAGE
