"""内置种子知识库：把公开渠道沉淀的高频补正/驳回问题预置为规则。

首次启动（kb_rules 为空）时自动灌入。来源：
- 中国版权保护中心鉴别材料格式要求（源程序每页50行、文档每页30行、页眉一致等）；
- 2026-03-15 新版申请表与 AI 声明新规、8 类非正常申请红线；
- 开源社区实战沉淀的高频补正清单（China-software-copyright 等）。

check_type=regex 的规则可被审查引擎自动执行；
其余规则注入所有生成 prompt 与 LLM 软审查，作为规避清单。
"""

SEED_RULES = [
    # ---------- 格式规范 ----------
    {"category": "格式规范", "problem": "源程序鉴别材料每页不足50行，或正文留有空行", "solution": "使用平台源代码文档引擎按每页50行重新排版导出，引擎已自动去除空行", "check_type": "none"},
    {"category": "格式规范", "problem": "源代码总页数超过60页时未按'前30页+后30页'截取，或不足60页时未全部提交", "solution": "由平台自动按规则截取，导出前在源代码页确认'将提交页数'", "check_type": "none"},
    {"category": "格式规范", "problem": "源代码文档最后一页不是程序结束页，末行以'{'等未闭合符号结尾", "solution": "引擎自动取代码尾部30页，保证末页即程序结束页；导出前平台会自动校验末行结束符", "check_type": "none"},
    {"category": "格式规范", "problem": "页眉未标注软件全称+版本号，或与申请表中的名称版本不一致", "solution": "docx 导出引擎自动在页眉写入与项目完全一致的'软件全称 版本号'，右上角自动生成页码", "check_type": "regex", "check_target": "version", "check_mode": "match", "check_pattern": r"^V\d+(\.\d+){0,2}$"},
    {"category": "格式规范", "problem": "版本号格式不规范（如写成 1.0、v1、V1.0.0.1），应为 V主版本.次版本 形式", "solution": "在项目信息中把版本号改为 V1.0 这类规范格式，申请表、页眉、说明书三处自动同步", "check_type": "regex", "check_target": "version", "check_mode": "match", "check_pattern": r"^V\d+(\.\d+){0,2}$"},
    {"category": "格式规范", "problem": "申请表'源程序量'字段漏写'行'字（写成 32101，应为 32101行）", "solution": "申请表生成时自动带'行'字后缀，人工核对申请表时保持一致", "check_type": "none"},
    {"category": "格式规范", "problem": "全部材料双面打印（审查要求单面打印）", "solution": "打印设置选单面；平台导出的材料清单中已列入打印检查项", "check_type": "none"},
    {"category": "格式规范", "problem": "文档鉴别材料每页不足30行（纯文字页），或页码未从目录开始连续编写", "solution": "说明书 docx 引擎按每页约30行排版；Word 里检查页码域从目录页开始连续编号", "check_type": "none"},
    {"category": "格式规范", "problem": "截图不清晰、带水印或被涂改，无法辨认界面内容", "solution": "使用系统原生截图工具截取全界面，分辨率不低于 1280x720，替换说明书中【截图占位】后再导出提交", "check_type": "none"},
    {"category": "格式规范", "problem": "说明书页数不足（建议正文不少于15页），或超过60页未做前后30页截取", "solution": "功能模块较多时逐模块生成操作说明扩充篇幅；超过60页由平台按前30后30截取导出", "check_type": "none"},
    {"category": "格式规范", "problem": "打印版申请表顶部缺少流水号条码", "solution": "必须在中国版权保护中心官网系统内在线填写后带流水号打印，不要用本地编辑的表格直接打印", "check_type": "none"},
    {"category": "格式规范", "problem": "补正通知发送至错误邮箱导致错过补正期限", "solution": "登记时使用常用邮箱并持续关注；未收到补正通知可致电版权中心补正组 010-84195640 核实", "check_type": "none"},

    # ---------- 材料一致性 ----------
    {"category": "材料一致性", "problem": "申请表、源程序页眉、说明书页眉三处的软件名称或版本号不一致（三重一致性校验不通过）", "solution": "统一在平台项目信息中修改名称/版本，所有材料由同一数据源重新生成，不要在 Word 里手改其中一处", "check_type": "regex", "check_target": "full_name", "check_mode": "match", "check_pattern": r"[\u4e00-\u9fa5A-Za-z0-9]{2,}"},
    {"category": "材料一致性", "problem": "软件名称不是以'系统/软件/平台/App/工具'等结尾，或含'中国、国家、中央、最高级'等禁用词", "solution": "调整为规范后缀命名并去除禁用词，例如'XX数据同步系统'", "check_type": "regex", "check_target": "full_name", "check_mode": "match", "check_pattern": r"(系统|软件|平台|App|APP|应用程序|管理软件|工具|引擎)$"},
    {"category": "材料一致性", "problem": "多人/多单位合作开发却在申请表中误选'独立开发'，且未附合作协议", "solution": "开发方式如实选择'合作开发/委托开发'，并上传签字盖章的合作/委托开发协议扫描件", "check_type": "none"},
    {"category": "材料一致性", "problem": "开发完成日期晚于首次发表日期，或开发完成日期填了未来时间", "solution": "核对日期逻辑：开发完成日期 <= 首次发表日期 <= 申请日期；未发表的填'未发表'", "check_type": "none"},
    {"category": "材料一致性", "problem": "申请表/说明书描述的功能在源代码中找不到对应实现，逻辑闭环断裂", "solution": "功能描述以代码分析结果为准逐模块对应；生成后用平台的'合规审查'预检三重一致性", "check_type": "none"},
    {"category": "材料一致性", "problem": "代码总行数与申请表填写的源程序量不匹配", "solution": "以平台统计的清洗后行数为准填写申请表，导出前不要手工增删源码文件", "check_type": "none"},

    # ---------- AI 声明与原创性（2026 新规重点） ----------
    {"category": "AI声明与原创性", "problem": "纯 AI 全自动生成的代码与文档直接提交（'AI冒充自研'属非正常申请，直接驳回并可能列入失信名单）", "solution": "对核心代码做人类实质性修改（架构调整、算法优化、注释写明设计意图），并如实填写 AI 声明为'AI辅助+人类实质性创作'", "check_type": "none"},
    {"category": "AI声明与原创性", "problem": "AI 声明勾选'全部为人类原创'，但代码呈现明显 AI 生成特征（模板化注释、风格单一），被审查认定材料不实", "solution": "声明口径与实际创作过程一致：使用平台的 AI 声明生成器按'AI辅助开发'口径生成，并附人类创作过程说明", "check_type": "none"},
    {"category": "AI声明与原创性", "problem": "代码注释为千篇一律的模板注释，无任何设计意图说明，被认定疑似 AI 生成", "solution": "核心模块注释改写为'为什么这样设计'（设计意图、取舍原因），删除 auto-generated / TODO 类噪音注释", "check_type": "regex", "check_target": "source", "check_mode": "forbid", "check_pattern": r"(?i)(auto[\s-]?generated|generated by|created by AI|作为AI|AI助手|语言模型|ChatGPT|Copilot)"},
    {"category": "AI声明与原创性", "problem": "源代码中残留 TODO/待实现/未完成的占位代码，末页出现未完成函数", "solution": "提交前全局搜索 TODO 并清理；确保代码可完整编译运行", "check_type": "regex", "check_target": "source", "check_mode": "forbid", "check_pattern": r"(?i)(TODO\s*[:：]|FIXME|待实现|待补全|此处省略|\.{3}省略)"},
    {"category": "AI声明与原创性", "problem": "缺少人类实质性创作的过程证据（Git 提交记录、开发日志、需求文档）", "solution": "使用平台'开发过程记录'生成器整理证据链；导入 Git log 还原真实开发时间线", "check_type": "none"},
    {"category": "AI声明与原创性", "problem": "同一主体短期内批量提交模板化材料（只换名称版本号），触发非正常申请预警，关联申请全部驳回", "solution": "控制申请节奏（同一主体单日不超过3件）；每件材料的功能描述、说明书内容必须基于该软件真实代码差异化生成", "check_type": "none"},
    {"category": "AI声明与原创性", "problem": "说明书是 AI 味浓厚的模板套话（每段都是'本模块实现了XX功能，界面友好'），无具体操作细节", "solution": "说明书按模块生成具体操作步骤（进入入口→字段说明→执行→结果确认），截图对应真实界面", "check_type": "none"},
    {"category": "AI声明与原创性", "problem": "代码与已登记软件或开源项目高度相似（仅改变量名/换皮），被相似度比对驳回", "solution": "对借鉴的开源代码做实质性二次开发，在材料中说明修改点；避免直接登记开源项目原样代码", "check_type": "none"},

    # ---------- 功能描述不足 ----------
    {"category": "功能描述不足", "problem": "申请表'主要功能描述'少于500字（2026 新版申请表硬性要求）", "solution": "使用申请表生成器按代码实际功能扩写到 500 字以上，逐条列出功能点及作用", "check_type": "regex", "check_target": "main_functions", "check_mode": "min_length", "check_value": 300},
    {"category": "功能描述不足", "problem": "开发目的空洞（'为了提高效率、方便管理'），无具体业务场景", "solution": "按'解决什么人群在什么场景下的什么问题→本软件如何解决'结构撰写，申请表生成器已内置该结构", "check_type": "none"},
    {"category": "功能描述不足", "problem": "说明书仅罗列功能名称，无操作步骤与界面说明", "solution": "每个功能模块补齐'功能说明/操作步骤/结果与注意事项'三段式内容，并配截图", "check_type": "none"},

    # ---------- 材料缺失 ----------
    {"category": "材料缺失", "problem": "缺少身份证明文件（企业未交盖章营业执照，个人未交身份证复印件）", "solution": "按材料清单核对：企业=营业执照复印件盖公章；个人=身份证正反面复印件", "check_type": "none"},
    {"category": "材料缺失", "problem": "有操作界面的软件未提交含截图的操作说明书，或无界面软件未提交设计说明", "solution": "有界面→生成操作说明书并替换真实截图；无界面（后台/SDK/引擎）→生成设计说明书", "check_type": "none"},
    {"category": "材料缺失", "problem": "合作/委托开发缺少经签字盖章的开发协议或权属约定条款", "solution": "协议中明确著作权归属；参考平台材料清单中的协议模板要点", "check_type": "none"},
    {"category": "材料缺失", "problem": "未提交 AI 使用情况声明材料（2026-03-15 起新版申请表必填）", "solution": "使用平台 AI 声明生成器生成声明正文，并准备 Git 记录等证据材料备查", "check_type": "none"},
    {"category": "材料缺失", "problem": "委托开发缺少委托协议，或职务开发未明确单位归属被要求补正权属证明", "solution": "补交委托开发合同或单位职务开发证明文件，权属约定与申请主体一致", "check_type": "none"},
    {"category": "材料缺失", "problem": "补正回复时只提交了出错部分，申请表某页填错却未整表重打签字", "solution": "申请表有误时整表重新打印并在指定页签字/盖章；其他材料可只交修正部分", "check_type": "none"},
]


def seed_if_empty(db) -> int:
    """kb_rules 表为空时灌入种子规则，返回灌入条数。"""
    if db.list_rules():
        return 0
    n = 0
    for r in SEED_RULES:
        check_config = {}
        if r.get("check_type") == "regex":
            check_config = {
                "target": r.get("check_target", ""),
                "mode": r.get("check_mode", "forbid"),
                "pattern": r.get("check_pattern", ""),
                "value": r.get("check_value", 0),
            }
        db.create_rule(case_id=None, project_id=None, category=r["category"],
                       problem=r["problem"], solution=r["solution"],
                       check_type=r.get("check_type", "none"), check_config=check_config)
        n += 1
    return n
